;HOWDY.ASM
;Author: Austin Smith
;TimeStampUnix: 1703736602
;GitHub.com/ThatSmittyDude
;puyinside.com
;ThatSmittyDude@outlook.com


DATA SEGMENT USE16              ;START OF DEFINED CONSTANTS, USE 16 BIT REGISTERS
MESG DB 'HOWDY','$'             ; 'DEFINE BYTES' AS MESSAGE "HOWDY" WITH "$"
DATA ENDS                       ;ENDS DEFINING CONSTANTS

CODE SEGMENT USE16              ;STARTS DEFINE INSTRUCTIONS, USE 16 BIT REGISTERS
    ASSUME CS:CODE,DS:DATA      ;ASSIGN VARIABLES CS FOR CODE DS FOR DAT

BEG:                            ;STARTS LOOP
    MOV AX,DATA                 ;MOVES THE DAT TO AX ACCUMULATOR
    MOV DS,AX                   ;MOVES THE DAT IN THE AX ACCUMUALTOR TO THE DAT SEGEMENT
    MOV AH,9                    ;MOVES ADDRESS TO THE AH ACCUMULATOR
    MOV DX,OFFSET MESG          ;OFFSETS MESSAGE TO THE DX DAT REGISTER?
    INT 21H                     ;SOFTWARE INTERUPT 21H (21 IN HEX), STILL ALLOWS ALL DOS SERVICES
    MOV AH,4CH                  ;MOVES THE VALUE OF 4CH (4C IN HEX) TO AH ACCUMULATOR
    INT 21H                     ;CAUSING SOFTWARE INTERUPT WHILST AH = 4C CAUSES CURRENT PROCESS TO TERMINATE
CODE ENDS                       ;END CODE SEGMENT
END BEG                         ;ENDS LOOP
